/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.educacao;

import com.educacao.dao.GenericDAO;
import com.educacao.dao.IGenericDAO;
import com.educacao.models.Endereco;
import com.educacao.models.Pessoa;
import com.educacao.models.Sexo;
import com.educacao.models.Telefone;
import javax.swing.JOptionPane;

/**
 *
 * @author cleys
 */
public class Application extends javax.swing.JFrame {
    public static Application app;
    private final IGenericDAO service;
    private Pessoa pessoa;

    /**
     * Creates new form Application
     */
    public Application() {
        initComponents();
        this.pessoa = new Pessoa();
        this.service = new GenericDAO();
    }
    
    public static void fromPessoa(Pessoa pessoa) {
        Application.app.limparDados();
        app.pessoa = pessoa;
        
        app.tx_nome.setText(pessoa.getNome());
        app.tx_idade.setText(String.valueOf(pessoa.getIdade()));
        
        int sexo;
        switch (pessoa.getSexo()) {
            case MASCULINO:
                sexo = 1;
                break;
            case FEMININO:
                sexo = 2;
                break;
                
            default:
                sexo = 0;
                break;
        }
        
        app.cb_sexo.setSelectedIndex(sexo);
        app.tx_telefone.setText(pessoa.getTelefone().getNumero());
        
        app.tx_logradouro.setText(pessoa.getEndereco().getLogradouro());
        app.tx_numero.setText(pessoa.getEndereco().getNumero());
        app.tx_bairro.setText(pessoa.getEndereco().getBairro());
        
        app.tx_cep.setText(pessoa.getEndereco().getCep());
        app.tx_cidade.setText(pessoa.getEndereco().getCidade());
        app.tx_complemento.setText(pessoa.getEndereco().getComplemento());
        
        int estado;
        switch(pessoa.getEndereco().getEstado()) {
            case "RJ":
               estado = 1;
               break;
               
            default:
                estado = 0;
                break;
        }
        
        app.cb_estado.setSelectedIndex(estado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_tabela = new javax.swing.JTabbedPane();
        jp_dados_cadastrais = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tx_nome = new javax.swing.JTextField();
        tx_idade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_sexo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tx_telefone = new javax.swing.JFormattedTextField();
        jp_endereco = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tx_logradouro = new javax.swing.JTextField();
        tx_numero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tx_bairro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tx_cidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cb_estado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tx_complemento = new javax.swing.JTextField();
        tx_cep = new javax.swing.JFormattedTextField();
        bt_limpar = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bt_visualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Educação");
        setResizable(false);

        jLabel2.setText("Nome");

        tx_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx_nomeKeyReleased(evt);
            }
        });

        tx_idade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx_idadeKeyReleased(evt);
            }
        });

        jLabel3.setText("Idade");

        cb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não Definido", "Masculino", "Feminino" }));
        cb_sexo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_sexoItemStateChanged(evt);
            }
        });
        cb_sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sexoActionPerformed(evt);
            }
        });

        jLabel4.setText("Sexo");

        jLabel11.setText("Telefone");

        try {
            tx_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tx_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_telefoneActionPerformed(evt);
            }
        });
        tx_telefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx_telefoneKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jp_dados_cadastraisLayout = new javax.swing.GroupLayout(jp_dados_cadastrais);
        jp_dados_cadastrais.setLayout(jp_dados_cadastraisLayout);
        jp_dados_cadastraisLayout.setHorizontalGroup(
            jp_dados_cadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_dados_cadastraisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_dados_cadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tx_nome)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_dados_cadastraisLayout.createSequentialGroup()
                        .addGroup(jp_dados_cadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tx_idade)
                            .addGroup(jp_dados_cadastraisLayout.createSequentialGroup()
                                .addGroup(jp_dados_cadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(0, 237, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_dados_cadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp_dados_cadastraisLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tx_telefone))
                .addContainerGap())
        );
        jp_dados_cadastraisLayout.setVerticalGroup(
            jp_dados_cadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_dados_cadastraisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tx_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jp_dados_cadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_dados_cadastraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tx_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jb_tabela.addTab("Dados Pessoais", jp_dados_cadastrais);

        jLabel5.setText("Logradouro");

        tx_logradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_logradouroActionPerformed(evt);
            }
        });
        tx_logradouro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx_logradouroKeyReleased(evt);
            }
        });

        tx_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_numeroActionPerformed(evt);
            }
        });
        tx_numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx_numeroKeyReleased(evt);
            }
        });

        jLabel6.setText("Número");

        tx_bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_bairroActionPerformed(evt);
            }
        });
        tx_bairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx_bairroKeyReleased(evt);
            }
        });

        jLabel7.setText("Bairro");

        tx_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_cidadeActionPerformed(evt);
            }
        });
        tx_cidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx_cidadeKeyReleased(evt);
            }
        });

        jLabel8.setText("Cidade");

        cb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "São Paulo", "Rio de Janeiro" }));
        cb_estado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_estadoItemStateChanged(evt);
            }
        });
        cb_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_estadoActionPerformed(evt);
            }
        });

        jLabel9.setText("Estado");

        jLabel10.setText("Complemento");

        jLabel12.setText("CEP");

        tx_complemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_complementoActionPerformed(evt);
            }
        });
        tx_complemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx_complementoKeyReleased(evt);
            }
        });

        try {
            tx_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tx_cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_cepActionPerformed(evt);
            }
        });
        tx_cep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tx_cepKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jp_enderecoLayout = new javax.swing.GroupLayout(jp_endereco);
        jp_endereco.setLayout(jp_enderecoLayout);
        jp_enderecoLayout.setHorizontalGroup(
            jp_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_enderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tx_complemento)
                    .addGroup(jp_enderecoLayout.createSequentialGroup()
                        .addComponent(tx_cidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp_enderecoLayout.createSequentialGroup()
                        .addGroup(jp_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tx_bairro, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tx_logradouro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tx_numero)
                            .addGroup(jp_enderecoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tx_cep)))
                    .addGroup(jp_enderecoLayout.createSequentialGroup()
                        .addGroup(jp_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_enderecoLayout.createSequentialGroup()
                                .addGroup(jp_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(311, 311, 311)
                                .addComponent(jLabel12))
                            .addComponent(jLabel10))
                        .addGap(0, 158, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jp_enderecoLayout.setVerticalGroup(
            jp_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_enderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_enderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tx_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tx_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jb_tabela.addTab("Endereço", jp_endereco);

        bt_limpar.setText("Limpar");
        bt_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limparActionPerformed(evt);
            }
        });

        bt_salvar.setText("Salvar");
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Educação 7.2.5 - Cadastro para recrutamento");

        bt_visualizar.setText("Visualizar");
        bt_visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_visualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_visualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_limpar))
                    .addComponent(jb_tabela, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_tabela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bt_visualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_estadoActionPerformed

    private void cb_sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sexoActionPerformed
        // TODO add your handling code here:
        try {
            this.pessoa.setSexo(Sexo.getFromIndex(cb_sexo.getSelectedIndex()));
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_cb_sexoActionPerformed

    private void tx_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_telefoneActionPerformed
        // TODO add your handling code here:
        this.pessoa.setTelefone(new Telefone.Builder().setNumero(tx_telefone.getText()).build());
    }//GEN-LAST:event_tx_telefoneActionPerformed

    private void tx_logradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_logradouroActionPerformed
        // TODO add your handling code here:
        Endereco end = this.pessoa.getEndereco();
        end.setLogradouro(tx_logradouro.getText());
        this.pessoa.setEndereco(end);
    }//GEN-LAST:event_tx_logradouroActionPerformed

    private void tx_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_numeroActionPerformed
        // TODO add your handling code here:
        Endereco end = this.pessoa.getEndereco();
        end.setNumero(tx_numero.getText());
        this.pessoa.setEndereco(end);
    }//GEN-LAST:event_tx_numeroActionPerformed

    private void tx_bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_bairroActionPerformed
        // TODO add your handling code here:
        Endereco end = this.pessoa.getEndereco();
        end.setBairro(tx_bairro.getText());
        this.pessoa.setEndereco(end);
    }//GEN-LAST:event_tx_bairroActionPerformed

    private void tx_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_cidadeActionPerformed
        // TODO add your handling code here:
        Endereco end = this.pessoa.getEndereco();
        end.setCidade(tx_cidade.getText());
        this.pessoa.setEndereco(end);
    }//GEN-LAST:event_tx_cidadeActionPerformed

    private void tx_complementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_complementoActionPerformed
        // TODO add your handling code here:
        Endereco end = this.pessoa.getEndereco();
        end.setComplemento(tx_complemento.getText());
        this.pessoa.setEndereco(end);
    }//GEN-LAST:event_tx_complementoActionPerformed

    private void bt_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparActionPerformed
        // TODO add your handling code here:
        this.limparDados();
    }//GEN-LAST:event_bt_limparActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        // TODO add your handling code here:
        System.out.println(this.pessoa);
        try {
            if (this.pessoa.getId() == null) {
                this.service.salvar(this.pessoa);
            } else {
                System.out.println("Editar");
                this.service.editar(this.pessoa);
            }
            
            JOptionPane.showMessageDialog(null, "Dados salvos!", "Cadastro", JOptionPane.PLAIN_MESSAGE);
            this.limparDados();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Falha ao Salvar dados!", "Falha", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void tx_nomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_nomeKeyReleased
        // TODO add your handling code here:
        this.pessoa.setNome(tx_nome.getText());
    }//GEN-LAST:event_tx_nomeKeyReleased

    private void tx_idadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_idadeKeyReleased
        // TODO add your handling code here:
        if (tx_idade.getText().length() <= 3) {
            try {
                this.pessoa.setIdade(Integer.parseInt(tx_idade.getText()));
            } catch (NumberFormatException e) {
                System.err.println(e);

                String tx = this.tx_idade.getText();
                this.tx_idade.setText(tx.substring(0, tx.length() - 1));
                JOptionPane.showMessageDialog(null, "Digite somente números", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            String tx = this.tx_idade.getText();
            this.tx_idade.setText(tx.substring(0, tx.length() - 1));
        }
        
        try {
            this.pessoa.setIdade(Integer.parseInt(this.tx_idade.getText()));
        } catch (NumberFormatException e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_tx_idadeKeyReleased

    private void cb_sexoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_sexoItemStateChanged
        try {
            // TODO add your handling code here:
            this.pessoa.setSexo(Sexo.getFromIndex(cb_sexo.getSelectedIndex()));
        } catch (Exception ex) {
            System.err.println(ex);
        }
    }//GEN-LAST:event_cb_sexoItemStateChanged

    private void tx_cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_cepActionPerformed

    private void tx_logradouroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_logradouroKeyReleased
        // TODO add your handling code here:
        Endereco end = this.pessoa.getEndereco();
        end.setLogradouro(tx_logradouro.getText());
        this.pessoa.setEndereco(end);
    }//GEN-LAST:event_tx_logradouroKeyReleased

    private void tx_telefoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_telefoneKeyReleased
        // TODO add your handling code here:
        Telefone tel = this.pessoa.getTelefone();
        tel.setNumero(this.tx_telefone.getText());
        this.pessoa.setTelefone(tel);
    }//GEN-LAST:event_tx_telefoneKeyReleased

    private void tx_numeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_numeroKeyReleased
        // TODO add your handling code here:
        Endereco end = this.pessoa.getEndereco();
        end.setNumero(tx_numero.getText());
        this.pessoa.setEndereco(end);
    }//GEN-LAST:event_tx_numeroKeyReleased

    private void tx_bairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_bairroKeyReleased
        // TODO add your handling code here:
        Endereco end = this.pessoa.getEndereco();
        end.setBairro(tx_bairro.getText());
        this.pessoa.setEndereco(end);
    }//GEN-LAST:event_tx_bairroKeyReleased

    private void tx_cepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_cepKeyReleased
        // TODO add your handling code here:
        Endereco end = this.pessoa.getEndereco();
        end.setCep(tx_cep.getText());
        this.pessoa.setEndereco(end);
    }//GEN-LAST:event_tx_cepKeyReleased

    private void tx_cidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_cidadeKeyReleased
        // TODO add your handling code here:
        Endereco end = this.pessoa.getEndereco();
        end.setCidade(tx_cidade.getText());
        this.pessoa.setEndereco(end);
    }//GEN-LAST:event_tx_cidadeKeyReleased

    private void cb_estadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_estadoItemStateChanged
        // TODO add your handling code here:
         Endereco end = this.pessoa.getEndereco();

        switch (cb_estado.getSelectedIndex()) {
            case 0:
                end.setEstado("SP");
                break;

            case 1:
                end.setEstado("RJ");
                break;

            default:
                System.err.println("Estado incorreto!");
        }

        this.pessoa.setEndereco(end);
    }//GEN-LAST:event_cb_estadoItemStateChanged

    private void tx_complementoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_complementoKeyReleased
        // TODO add your handling code here:
        Endereco end = this.pessoa.getEndereco();
        end.setComplemento(tx_complemento.getText());
        this.pessoa.setEndereco(end);
    }//GEN-LAST:event_tx_complementoKeyReleased

    private void bt_visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_visualizarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Tabela.run();
    }//GEN-LAST:event_bt_visualizarActionPerformed

    /**
     * Limpa todo o formulário
     */
    private void limparDados() {
        jb_tabela.setSelectedIndex(0);
        
        tx_bairro.setText(null);
        tx_cep.setText(null);
        tx_cidade.setText(null);
        tx_complemento.setText(null);
        tx_idade.setText(null);
        tx_logradouro.setText(null);
        tx_nome.setText(null);
        tx_numero.setText(null);
        tx_telefone.setText(null);

        cb_estado.setSelectedIndex(0);
        cb_sexo.setSelectedIndex(0);

        this.pessoa = new Pessoa();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Application.app = new Application();
                app.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_limpar;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JButton bt_visualizar;
    private javax.swing.JComboBox<String> cb_estado;
    private javax.swing.JComboBox<String> cb_sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jb_tabela;
    private javax.swing.JPanel jp_dados_cadastrais;
    private javax.swing.JPanel jp_endereco;
    private javax.swing.JTextField tx_bairro;
    private javax.swing.JFormattedTextField tx_cep;
    private javax.swing.JTextField tx_cidade;
    private javax.swing.JTextField tx_complemento;
    private javax.swing.JTextField tx_idade;
    private javax.swing.JTextField tx_logradouro;
    private javax.swing.JTextField tx_nome;
    private javax.swing.JTextField tx_numero;
    private javax.swing.JFormattedTextField tx_telefone;
    // End of variables declaration//GEN-END:variables
}
